linters:
  Comment:
    allowed: '(Copyright)|(\.scss[ */]*$)|(@noflip)'
  DeclarationOrder:
    enabled: false
  DisableLinterReason:
    enabled: true
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  MergeableSelector:
    force_nesting: false
  NameFormat:
    enabled: false
  NestingDepth:
    max_depth: 6
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
    max_depth: 6
  SelectorFormat:
    enabled: false
  Shorthand:
    allowed_shorthands: [1,2,4]
  SpaceAfterPropertyColon:
    enabled: false
    style: one_space_or_newline
  TrailingSemicolon:
    enabled: false
  TransitionAll:
    enabled: true
  UnnecessaryMantissa:
    enabled: false
  UrlFormat:
    enabled: false
  VendorPrefix:
    enabled: false